name: smart_home
description: A new Flutter project for Smart Home Application.
version: 1.0.0+1

publish_to: 'none'  # Remove this line if you plan to publish your app

environment:
  sdk: ">=2.17.6 <3.0.0"  # Make sure this matches your SDK version

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  firebase_analytics: ^11.4.0

  # Other dependencies
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true