name: smart_home
description: A new Flutter project for Smart Home Application.
version: 1.0.0+1

publish_to: 'none' # Remove this line if you plan to publish your app

environment:
  sdk: ">=2.17.0 <3.0.0" # Updated Dart SDK version for better compatibility

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  firebase_analytics: ^11.4.0
  flutter_local_notifications: 18.0.1
  # Other dependencies
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  http: ^1.2.2
  awesome_dialog: ^3.2.1
  url_launcher: ^6.3.1
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Updated for compatibility with the Dart SDK

flutter:
  uses-material-design: true
